### ISSUE TITLE
Pullover 1.3.0 not compatible with OS X 10.8.x.

### ISSUE THREAD

**Issue by trych** [cgrossde/Pullover#128]
Hi there,
contrary to the statement on the Github page, Pullover 1.3.0 does *not* seem to be compatible with Mac OS X 10.8.

When I open the image, the app icon is shown with the forbidden icon, so I cannot open the app.

Any way to still run this on 10.8?

**Comment by cgrossde** [comment]
Try righclick then open
Am 26. Nov. 2018, 11:20 +0100 schrieb trych <notifications@github.com>:

Hi there,
contrary to the statement on the Github page, Pullover 1.3.0 does not seem to be compatible with Mac OS X 10.8.

When I open the image, the app icon is shown with the forbidden icon, so I cannot open the app.

Any way to still run this on 10.8?

**Comment by cgrossde** [comment]
In that case either downgrade pullover or update your OS. I usually give no support for Pullover since it’s a project done in my free time. If I give support then only for the latest OS
Am 27. Nov. 2018, 00:29 +0100 schrieb trych <notifications@github.com>:

I did. It gives me the message that it requires 10.9 or later. See attached images.

[pullover]<https://user-images.githubusercontent.com/9803905/49048531-61752880-f1db-11e8-94b4-4d8d2be82d07.png>

[pullover2]<https://user-images.githubusercontent.com/9803905/49048540-676b0980-f1db-11e8-9e6e-dcfbdfce4b0d.png>

**Comment by trych** [comment]
Sure, that's absolutely fine.
Maybe you could update the requirements info in the README.md, so other people will not be confused.

Thanks for your work on this project!

**Comment by cgrossde** [comment]
Sorry about that, updated the readme :) Thanks for trying it out.

**Comment by cgrossde** [comment]
Try v1.2.0: https://github.com/cgrossde/Pullover/releases/tag/1.2.0 
It uses an older NW.js and might still be compatible with 10.8
