### ISSUE TITLE
Messages are not recorded in OS X notification centre.

### ISSUE THREAD

**Issue by Sergicles** [cgrossde/Pullover#17]
Upon receiving a desktop notification, messages are not shown in notification centre, on OS X 10.10 Yosemite.

Cheers 
   Serg

**Comment by cgrossde** [comment]
Could you please check your notification center settings for Pullover. Because if you see them pop up then they should also be in the notification center unless you deactivated it. The screenshot is german but look out for something like "In Notification Center" with a dropdown next to it.

![bildschirmfoto 2015-02-01 um 14 30 00](https://cloud.githubusercontent.com/assets/2333584/5992195/e1cd2464-aa1e-11e4-8c9b-540b8b35f5de.png)

**Comment by Sergicles** [comment]
Screen shots attached.

FYI, using v0.3.1.

![screen shot 2015-02-02 at 12 38 35 am](https://cloud.githubusercontent.com/assets/4461395/5992242/1cabdde0-aa75-11e4-83d1-68b753a9a01c.jpg)
![screen shot 2015-02-02 at 12 38 58 am](https://cloud.githubusercontent.com/assets/4461395/5992243/1caecd8e-aa75-11e4-9c13-5b01c3621864.jpg)
![screen shot 2015-02-02 at 12 39 10 am](https://cloud.githubusercontent.com/assets/4461395/5992244/1cafa93e-aa75-11e4-867e-b0db765fbd97.jpg)

**Comment by cgrossde** [comment]
Ahhh, now I understand. I might need some more documentation for Pullover.

Here's the deal: I made the new notification system for the windows users, because on windows there is no notification center. **That means for all Mac OS users: Don't activate the "Use new notifications" option**. Then it will start using the native Mac notification center again and you will have a history there.

**Comment by macskull70** [comment]
My first question; how do you know that it isn't working correctly?  I
didn't send or ask for any help. Clueless and little freaked out. Please
Explain

**Comment by macskull70** [comment]
My first question; how do you know that it isn't working correctly?  I
didn't send or ask for any help. Clueless and little freaked out. Please
Explain

**Comment by cgrossde** [comment]
I have no idea how you got that message, did you add this project to your watched projects?

**Comment by macskull70** [comment]
I don't think so; but new to github. Assuming from the watch list comment you made, that when adding any item to watch-list it becomes a support ticket?

**Comment by macskull70** [comment]
Now I know. Thanks
