### ISSUE TITLE
Signcode ENOENT

### ISSUE THREAD

**Issue by jonaswindey** [cgrossde/Pullover#30]
Great work on this project and thanks for open-sourcing it.

I'm trying to use this program as a starter kit for another project, and I'm getting an error when building the windows installer:

```
Windows installer created
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn signcode ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

Looking at the builder file, it looks like I need to have a .crt and .spc in /res , but even if there are files there, the error occurs.

I'm using OS X and have installed the items from CROSSPLATFORM.md

**Comment by cgrossde** [comment]
I don't know the origin of this error but remove lines 350 to 374 (of the original builder file of course) which relate to signing the installer with a certificate. If you don't have a certificate you don't need those lines. 

I will close this issue since it is not directly related to Pullover but feel free to comment if you need more help.
