### ISSUE TITLE
Setting Pullover alert style in Notification Center to Alert causes duplicate notifications

### ISSUE THREAD

**Issue by ALinuxNinja** [cgrossde/Pullover#37]
If the alert style for pullover in the notification center is set to 'Alerts', Pullover shows the notification twice.

**Comment by cgrossde** [comment]
Can't reproduce this issue on El Captain 10.11.2

**Comment by ALinuxNinja** [comment]
I'm running 10.11.3

Tried it again on another installation - not occuring.

Must be only happening on this particular installation, ignore this issue.

**Comment by ALinuxNinja** [comment]
Update:

I am seeing it now on random notifications. Attached is a screenshot.

Now that I think about it, it might be due to the fact that I am on a VPN

![2016-02-08_15-50-48](https://cloud.githubusercontent.com/assets/9060865/12898659/e587b434-ce7b-11e5-9485-545dbaa95101.png)

**Comment by cgrossde** [comment]
I suspect that this issue happens regardless of the notification style but since the alert notifications stay on screen you only notice it with that setting. Pullover needs to confirm the reception of notifications to Pushover. If something happens with your connection directly after downloading the newest notifications the confirmation may fail. In that case it will show up a second time when Pullover fetches new notifications because pushover never got the reception confirmation.

I'm almost done with a complete rewrite of Pullover, so please wait for the release. I don't have an ETA yet.

**Comment by cgrossde** [comment]
Please try the new alpha, it's a complete rewrite: 
https://github.com/cgrossde/Pullover/releases/tag/1.0.0-alpha.1
