### ISSUE TITLE
Notification sounds with native notifications on OSX

### ISSUE THREAD

**Issue by jens-maus** [cgrossde/Pullover#46]
I don't know if this might be a bug or simply a missing feature or me using OSX notifications incorrectly. But here a pushover message is only received with playing the adequate pushover sound if Pullovers' now notification system is used. As soon as I switch to native OSX notifications no sound whatsoever is played.

It would be great if that feature could be implemented for the final 1.0.0 version. here I am using the beta1 version of 1.0.0, btw.

**Comment by cgrossde** [comment]
I tried to do that. The problem is that OS X provides no callback for the 'show' event which could be used to play a sound. I need to do some more testing because I suspect OS X shows the notification immediately. In that case we need some notification buffering so that not all notification are shown at once and we could play the sound just before dispatching it to the OS X notification center.

**Comment by jens-maus** [comment]
This sounds good to me. However, please make sure not to play 100 consecutive sounds if there are 100 pending pushover messages you are about to dispatch to the OSX notification center or to the Pullovers' own notifications because otherwise this might end up in a long, disturbing sequence of different sounds being played. One sound (or at a max. just all different sounds) for each notification dispatching round would/should be enough.

**Comment by cgrossde** [comment]
There is a setting for that: 
![bildschirmfoto 2016-03-09 um 13 45 26](https://cloud.githubusercontent.com/assets/2333584/13635607/36770bf4-e5fd-11e5-8f1b-dfc69297e044.png)
If you login to your computer and 100 notifications are due only the last 20 will be shown. 
I won't implement grouping because notifications are processed sequentially.

**Comment by jens-maus** [comment]
That's clear, but it would be great to have a possibility that not 20 sounds are being played just because 20 messages are waiting. IMHO it doesn't make sense to play 20 sounds because these 20 notifications will be appear at the same time anyway. So a single sound (or only the different sounds) should be played once only.

**Comment by jens-maus** [comment]
Any progress on sound for native OSX notifications with pullover?

**Comment by cgrossde** [comment]
Thanks for reporting this. Sound will now also be played when using native notifications. Also sound throttling was implemented, the same sound is not played twice in a 10 sec window. Please try the new version: [1.0.0-beta.2](https://github.com/cgrossde/Pullover/releases/tag/1.0.0-beta.2)
