### ISSUE TITLE
Fatal error occurred

### ISSUE THREAD

**Issue by realcanadrian** [cgrossde/Pullover#53]
The pullover beta 1.0.0-beta.2 on OS X 10.11.5 told me to post this here.

[pullover.1.log.zip](https://github.com/cgrossde/Pullover/files/278310/pullover.1.log.zip)

**Comment by sejmann** [comment]
I actually had the exact same error at the exact same moment -- I assume that the server returned an HTML error page briefly while the service was restarting, or some similar cause.

![screenshot of sublime text 5-23-16 10-35-38 pm](https://cloud.githubusercontent.com/assets/1660933/15493129/b45c1c7a-2136-11e6-87b2-3700f64f20c6.png)

(One trivial and unrelated difference between our logs is that mine showed the period in the event.js file name in the stack rather than eventjs, with out the period as in @realcanadrian's log. I can't imagine where the period went.)

**Comment by cgrossde** [comment]
Thanks for reporting this. Yes, I think there was some error on the server. See #52
