### ISSUE TITLE
Feature: add tickbox in config for notification timestamp prefixes.

### ISSUE THREAD

**Issue by pbosgraaf** [cgrossde/Pullover#58]
Would it be possible to create an extra checkbox in the configuration menu that would add a timestamp prefix (preferably the send timestamp, not the received) to received notifications?

This would allow the user to instantly see if received notifications are relevant when it's a time critical notification.

**Comment by cgrossde** [comment]
This would be possible but I won't implement it because:
- very specific feature which might only be used by a few users
- I want to keep the options to a minimum
- Notifications should be concise and show only the most important information. The TS might sometimes be important but in most cases it isn't.

However this project is open source so feel free to fork and modify it.
